import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

interface PDFOptions {
  title: string;
  subtitle?: string;
  content: string[];
  filename?: string;
}

export const exportToPDF = ({ title, subtitle, content, filename = 'calculation.pdf' }: PDFOptions) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFillColor(0, 68, 148); // Primary color
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('TRESDTRES LAB', 20, 25);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('PRECISION INSTRUMENTATION SK-1', 20, 32);
  
  // Content
  doc.setTextColor(33, 33, 33);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 20, 55);
  
  if (subtitle) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(subtitle, 20, 62);
  }
  
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 68, 190, 68);
  
  doc.setFontSize(11);
  doc.setTextColor(50, 50, 50);
  doc.setFont('courier', 'normal');
  
  let y = 80;
  content.forEach((line) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, 20, y);
    y += 8;
  });
  
  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by TRESDTRES LAB SK-1 Stable - Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
  }
  
  doc.save(filename);
};
